export const GOOGLE_ADS_ID =
  process.env.NEXT_PUBLIC_GOOGLE_ADS_ID || "AW-18095488131";

export const GOOGLE_ADS_PURCHASE_CONVERSION_LABEL =
  process.env.NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_LABEL || "NSxACK-gva8cEIP5zLRD";

export const GOOGLE_ADS_PURCHASE_SEND_TO =
  `${GOOGLE_ADS_ID}/${GOOGLE_ADS_PURCHASE_CONVERSION_LABEL}`;
